from datetime import datetime, timedelta, timezone

ASSETS = [
    {
        "asset_id": "asset-bfp-101",
        "asset_name": "Boiler Feed Pump 101",
        "site": "NorthPlant",
        "unit": "Unit 1",
        "asset_type": "pump",
        "criticality": "high",
        "description": "Main boiler feed water pump",
        "related_asset_ids": ["asset-motor-101", "asset-valve-101"],
    },
    {
        "asset_id": "asset-bfp-102",
        "asset_name": "Boiler Feed Pump 102",
        "site": "NorthPlant",
        "unit": "Unit 1",
        "asset_type": "pump",
        "criticality": "high",
        "description": "Backup boiler feed water pump",
        "related_asset_ids": ["asset-motor-102", "asset-valve-102"],
    },
    {
        "asset_id": "asset-compressor-201",
        "asset_name": "Compressor 201",
        "site": "EastRefinery",
        "unit": "Unit 2",
        "asset_type": "compressor",
        "criticality": "critical",
        "description": "Process gas compressor",
        "related_asset_ids": ["asset-motor-201"],
    },
    {
        "asset_id": "asset-motor-101",
        "asset_name": "Motor 101",
        "site": "NorthPlant",
        "unit": "Unit 1",
        "asset_type": "motor",
        "criticality": "high",
        "description": "Drive motor for Boiler Feed Pump 101",
        "related_asset_ids": ["asset-bfp-101"],
    },
]

ALARMS = [
    {
        "alarm_id": "alarm-bfp101-low-flow-001",
        "asset_id": "asset-bfp-101",
        "alarm_name": "Boiler Feed Pump Low Flow",
        "severity": "critical",
        "status": "active",
        "alarm_type": "process",
        "message": "Feed water flow below configured limit",
        "start_time": "2026-06-28T10:00:00Z",
        "ack_time": None,
        "occurrence_count": 12,
    },
    {
        "alarm_id": "alarm-bfp101-discharge-pressure-001",
        "asset_id": "asset-bfp-101",
        "alarm_name": "Pump Discharge Pressure Low",
        "severity": "high",
        "status": "historical",
        "alarm_type": "process",
        "message": "Pump discharge pressure repeatedly below limit",
        "start_time": "2026-06-20T08:00:00Z",
        "ack_time": "2026-06-20T08:04:00Z",
        "occurrence_count": 18,
    },
    {
        "alarm_id": "alarm-bfp102-trip-001",
        "asset_id": "asset-bfp-102",
        "alarm_name": "Boiler Feed Pump Motor Trip",
        "severity": "critical",
        "status": "active",
        "alarm_type": "equipment",
        "message": "Motor protection relay has tripped",
        "start_time": "2026-06-29T14:30:00Z",
        "ack_time": None,
        "occurrence_count": 3,
    },
    {
        "alarm_id": "alarm-compressor-pressure-001",
        "asset_id": "asset-compressor-201",
        "alarm_name": "Compressor Discharge Pressure High",
        "severity": "high",
        "status": "active",
        "alarm_type": "process",
        "message": "Compressor discharge pressure exceeds operating limit",
        "start_time": "2026-06-29T13:00:00Z",
        "ack_time": None,
        "occurrence_count": 9,
    },
]
